name: 'Terraform'

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
  workflow_dispatch:  # This allows you to manually trigger the workflow

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'  # Skip this job if the workflow is manually triggered

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version of Terraform you are using

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Save Terraform State File
        uses: actions/upload-artifact@v2
        with:
          name: terraform-state
          path: terraform.tfstate

  destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'  # Only run this job when manually triggered

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Terraform State File
        uses: actions/download-artifact@v2
        with:
          name: terraform-state
          path: .

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version of Terraform you are using

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
