name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  id-token: write  # Required for Azure login

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Terraform environment variables
        run: |
          echo "Setting up Terraform Authentication..."
          echo 'AZURE_CREDENTIALS=${{ secrets.AZURE_CREDENTIALS }}' >> $GITHUB_ENV
          echo 'ARM_CLIENT_ID=$(echo $AZURE_CREDENTIALS | jq -r .clientId)' >> $GITHUB_ENV
          echo 'ARM_CLIENT_SECRET=$(echo $AZURE_CREDENTIALS | jq -r .clientSecret)' >> $GITHUB_ENV
          echo 'ARM_TENANT_ID=$(echo $AZURE_CREDENTIALS | jq -r .tenantId)' >> $GITHUB_ENV
          echo 'ARM_SUBSCRIPTION_ID=$(echo $AZURE_CREDENTIALS | jq -r .subscriptionId)' >> $GITHUB_ENV

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
