name: 'Terraform'

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  pull_request:
  workflow_dispatch:  # This allows you to manually trigger the workflow

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify the version of Terraform you are using

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Terraform Apply or Destroy
        id: apply_or_destroy
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            terraform destroy -auto-approve
          else
            terraform apply -auto-approve
          fi
